#include "cloudiff/runtime_executor.hpp"
#include <boost/asio.hpp>
#include <boost/beast.hpp>
#include <algorithm>
#include <array>
#include <cerrno>
#include <chrono>
#include <cctype>
#include <csignal>
#include <cstdlib>
#include <poll.h>
#include <regex>
#include <stdexcept>
#include <string>
#include <sys/wait.h>
#include <unistd.h>

namespace cloudiff {
namespace asio=boost::asio;
namespace beast=boost::beast;
namespace http=beast::http;
using tcp=asio::ip::tcp;
namespace {
constexpr std::size_t kMaxBody=64*1024;
constexpr std::size_t kMaxCapture=65536;
std::string env_or(const char* name,std::string fallback={}){const char* v=std::getenv(name);return v?std::string(v):std::move(fallback);}
int env_int(const char* name,int fallback,int lo,int hi){try{return std::clamp(std::stoi(env_or(name,std::to_string(fallback))),lo,hi);}catch(...){return fallback;}}
bool env_bool(const char* name,bool fallback){auto v=env_or(name);if(v.empty())return fallback;std::transform(v.begin(),v.end(),v.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));});return v=="1"||v=="true"||v=="yes"||v=="on";}
bool constant_time_equal(std::string_view a,std::string_view b){unsigned char diff=static_cast<unsigned char>(a.size()^b.size());const auto n=std::max(a.size(),b.size());for(std::size_t i=0;i<n;++i){const auto x=i<a.size()?static_cast<unsigned char>(a[i]):0;const auto y=i<b.size()?static_cast<unsigned char>(b[i]):0;diff=static_cast<unsigned char>(diff|(x^y));}return diff==0;}
bool valid_execution_id(std::string_view v){static const std::regex re("^rt_[0-9a-f]{20}$");return std::regex_match(v.begin(),v.end(),re);}
bool valid_image_id(std::string_view v){static const std::regex re("^sha256:[0-9a-f]{64}$");return std::regex_match(v.begin(),v.end(),re);}
bool valid_sha(std::string_view v){static const std::regex re("^[0-9a-f]{64}$");return std::regex_match(v.begin(),v.end(),re);}
bool rootless_user(std::string_view user){if(user.empty())return false;const auto pos=user.find(':');const auto first=user.substr(0,pos);return first!="0"&&first!="root";}
void append_limited(std::string& out,const char* data,std::size_t size){if(out.size()>=kMaxCapture)return;out.append(data,std::min(size,kMaxCapture-out.size()));}
RuntimeCommandResult run_command(const std::vector<std::string>& command,int timeout_seconds){
    if(command.empty())throw std::invalid_argument("command_empty");int out_pipe[2]{},err_pipe[2]{};if(pipe(out_pipe)!=0||pipe(err_pipe)!=0)throw std::runtime_error("pipe_failed");
    const pid_t pid=fork();if(pid<0)throw std::runtime_error("fork_failed");
    if(pid==0){(void)dup2(out_pipe[1],STDOUT_FILENO);(void)dup2(err_pipe[1],STDERR_FILENO);close(out_pipe[0]);close(out_pipe[1]);close(err_pipe[0]);close(err_pipe[1]);std::vector<char*> argv;argv.reserve(command.size()+1);for(const auto& p:command)argv.push_back(const_cast<char*>(p.c_str()));argv.push_back(nullptr);execvp(argv[0],argv.data());_exit(127);}
    close(out_pipe[1]);close(err_pipe[1]);RuntimeCommandResult result;const auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(std::max(1,timeout_seconds));bool exited=false;int status=0;std::array<char,4096> buf{};
    while(true){pollfd fds[2]{{out_pipe[0],POLLIN|POLLHUP,0},{err_pipe[0],POLLIN|POLLHUP,0}};(void)poll(fds,2,50);for(int i=0;i<2;++i){if(!(fds[i].revents&(POLLIN|POLLHUP)))continue;const auto n=read(fds[i].fd,buf.data(),buf.size());if(n>0)append_limited(i==0?result.stdout_text:result.stderr_text,buf.data(),static_cast<std::size_t>(n));}
        if(!exited){const auto r=waitpid(pid,&status,WNOHANG);if(r==pid)exited=true;else if(r<0&&errno!=EINTR)throw std::runtime_error("waitpid_failed");}
        if(!exited&&std::chrono::steady_clock::now()>=deadline){kill(pid,SIGKILL);(void)waitpid(pid,&status,0);close(out_pipe[0]);close(err_pipe[0]);throw std::runtime_error("command_timeout");}
        if(exited){for(int fd:{out_pipe[0],err_pipe[0]}){while(true){const auto n=read(fd,buf.data(),buf.size());if(n>0)append_limited(fd==out_pipe[0]?result.stdout_text:result.stderr_text,buf.data(),static_cast<std::size_t>(n));else break;}}break;}
    }
    close(out_pipe[0]);close(err_pipe[0]);result.exit_code=WIFEXITED(status)?WEXITSTATUS(status):(WIFSIGNALED(status)?128+WTERMSIG(status):255);return result;
}
void require_ok(const RuntimeCommandResult& r,const char* code){if(r.exit_code!=0)throw std::runtime_error(code);}
nlohmann::json parse_first(const RuntimeCommandResult& r,const char* code){require_ok(r,code);auto x=nlohmann::json::parse(r.stdout_text);if(!x.is_array()||x.empty()||!x.at(0).is_object())throw std::runtime_error(code);return x.at(0);}
bool array_contains(const nlohmann::json& value,std::string_view expected){if(!value.is_array())return false;for(const auto& item:value)if(item.is_string()&&item.get<std::string>()==expected)return true;return false;}
nlohmann::json common_security(){return {{"user","65532:65532"},{"read_only",true},{"cap_drop",nlohmann::json::array({"ALL"})},{"no_new_privileges",true},{"published_ports",nlohmann::json::array()}};}
nlohmann::json profile_base(bool mutation,bool activation,const char* traffic,const char* network,int memory,int pids,int tmpfs,int ttl_min,int ttl_max,bool pre,bool post,bool external,bool rollback,bool remove){return {{"mutation_allowed",mutation},{"activation_allowed",activation},{"traffic_scope",traffic},{"network",network},{"memory_mib",memory},{"pids",pids},{"tmpfs_mib",tmpfs},{"ttl_min_seconds",ttl_min},{"ttl_max_seconds",ttl_max},{"pre_switch_smoke",pre},{"post_switch_smoke",post},{"external_health_match",external},{"rollback_required",rollback},{"remove_after_execution",remove},{"security",common_security()}};}
RuntimeResponse execute_canary(const RuntimeExecutorOptions& options,RuntimeProfile profile,const nlohmann::json& request){
    const auto execution=request.value("execution_id",std::string{}),image=request.value("artifact_image_id",std::string{}),source=request.value("immutable_source_digest",std::string{});
    if(!valid_execution_id(execution)||!valid_image_id(image)||!valid_sha(source))return {422,{{"ok",false},{"error","invalid_runtime_identity"},{"secrets_exposed",false}}};
    int ttl=0;if(profile==RuntimeProfile::PREVIEW){ttl=3600;try{if(request.contains("ttl_seconds"))ttl=request.at("ttl_seconds").get<int>();}catch(...){return {422,{{"ok",false},{"error","invalid_ttl"}}};}if(ttl<300||ttl>86400)return {422,{{"ok",false},{"error","ttl_not_allowed"}}};}else if(request.contains("ttl_seconds"))return {422,{{"ok",false},{"error","ttl_only_allowed_for_preview"}}};
    const std::string name="cloudiff-v18-"+execution.substr(3);const auto& runner=options.command_runner;bool started=false;
    try{
        const auto image_info=parse_first(runner({"docker","image","inspect",image},30),"image_inspect_failed");if(image_info.value("Id","")!=image)throw std::runtime_error("image_identity_mismatch");const auto user=image_info.value("Config",nlohmann::json::object()).value("User","");if(!rootless_user(user))return {409,{{"ok",false},{"error","artifact_image_not_rootless"},{"secrets_exposed",false}}};
        (void)runner({"docker","rm","-f",name},30);
        const std::string network=profile==RuntimeProfile::TEST?"none":"cloudif-publications";
        std::vector<std::string> cmd={"docker","run","-d","--name",name,"--network",network,"--read-only","--user","65532:65532","--tmpfs","/tmp:rw,noexec,nosuid,size=16m,mode=1777","--memory","128m","--pids-limit","128","--cap-drop","ALL","--security-opt","no-new-privileges","--label","org.cloudiff.runtime-execution="+execution,"--label","org.cloudiff.runtime-profile="+runtime_profile_name(profile),"--label","org.cloudiff.immutable-source-digest="+source,image};
        require_ok(runner(cmd,120),"container_create_failed");started=true;
        const auto c=parse_first(runner({"docker","inspect",name},30),"container_inspect_failed");const auto config=c.value("Config",nlohmann::json::object());const auto host=c.value("HostConfig",nlohmann::json::object());const auto state=c.value("State",nlohmann::json::object());const auto net=c.value("NetworkSettings",nlohmann::json::object());
        if(!state.value("Running",false)||config.value("User","")!="65532:65532"||!host.value("ReadonlyRootfs",false)||host.value("NetworkMode","")!=network||host.value("Memory",0LL)!=134217728LL||host.value("PidsLimit",0LL)!=128LL||!array_contains(host.value("CapDrop",nlohmann::json::array()),"ALL")||!array_contains(host.value("SecurityOpt",nlohmann::json::array()),"no-new-privileges")||!host.value("Tmpfs",nlohmann::json::object()).contains("/tmp"))throw std::runtime_error("container_policy_mismatch");
        bool published=false;const auto bindings=host.value("PortBindings",nlohmann::json::object());if(bindings.is_object())for(auto it=bindings.begin();it!=bindings.end();++it){const auto& v=it.value();if((v.is_array()||v.is_object())&&!v.empty())published=true;}const auto ports=net.value("Ports",nlohmann::json::object());if(ports.is_object())for(auto it=ports.begin();it!=ports.end();++it){const auto& v=it.value();if(!v.is_null()&&((v.is_array()||v.is_object())?!v.empty():true))published=true;}if(published)throw std::runtime_error("published_ports_not_allowed");
        require_ok(runner({"docker","rm","-f",name},30),"container_cleanup_failed");started=false;const auto absent=runner({"docker","inspect",name},30);if(absent.exit_code==0)throw std::runtime_error("container_cleanup_unconfirmed");
        nlohmann::json result={{"ok",true},{"profile",runtime_profile_name(profile)},{"execution_id",execution},{"artifact_image_id",image},{"immutable_source_digest",source},{"network",network},{"container_running",false},{"container_removed",true},{"public_traffic_activated",false},{"published_ports",nlohmann::json::array()},{"security",common_security()},{"secrets_exposed",false}};if(profile==RuntimeProfile::PREVIEW)result["ttl_seconds"]=ttl;return {200,std::move(result)};
    }catch(const std::exception& e){if(started)(void)runner({"docker","rm","-f",name},30);return {500,{{"ok",false},{"error","runtime_canary_failed"},{"detail",e.what()},{"container_removed",true},{"public_traffic_activated",false},{"secrets_exposed",false}}};}
}
}
std::optional<RuntimeProfile> runtime_profile_from_string(std::string_view value){if(value=="PREVIEW")return RuntimeProfile::PREVIEW;if(value=="TEST")return RuntimeProfile::TEST;if(value=="HOMOLOGATION")return RuntimeProfile::HOMOLOGATION;if(value=="CANARY")return RuntimeProfile::CANARY;if(value=="PRODUCTION")return RuntimeProfile::PRODUCTION;if(value=="SEALED")return RuntimeProfile::SEALED;return std::nullopt;}
std::string runtime_profile_name(RuntimeProfile profile){switch(profile){case RuntimeProfile::PREVIEW:return "PREVIEW";case RuntimeProfile::TEST:return "TEST";case RuntimeProfile::HOMOLOGATION:return "HOMOLOGATION";case RuntimeProfile::CANARY:return "CANARY";case RuntimeProfile::PRODUCTION:return "PRODUCTION";case RuntimeProfile::SEALED:return "SEALED";}throw std::logic_error("unknown runtime profile");}
nlohmann::json runtime_profile_policy(RuntimeProfile profile){nlohmann::json p;switch(profile){case RuntimeProfile::PREVIEW:p=profile_base(true,true,"preview-proxy","cloudif-publications",128,128,16,300,86400,true,false,false,false,false);break;case RuntimeProfile::TEST:p=profile_base(true,false,"none","none",128,128,16,0,0,true,false,false,false,true);break;case RuntimeProfile::HOMOLOGATION:p=profile_base(true,true,"homologation-proxy","cloudif-publications",128,128,16,0,0,true,true,false,true,false);p["network_alias"]="cloudif-prod-homologation";break;case RuntimeProfile::CANARY:p=profile_base(true,true,"internal-canary","cloudif-production-canary",128,128,16,0,0,true,true,false,true,false);p["network_alias"]="cloudif-prod-canary";break;case RuntimeProfile::PRODUCTION:p=profile_base(true,true,"public-production","cloudif-publications",192,160,16,0,0,true,true,true,true,false);p["network_alias"]="cloudif-production-active";break;case RuntimeProfile::SEALED:p=profile_base(false,false,"none","none",0,0,0,0,0,false,false,false,false,false);p["sealed"]=true;p["production_effects_enabled"]=false;p["artifact_alias_attached"]=false;p["restore_validation_required"]=true;p["monitoring_required"]=true;break;}p["profile"]=runtime_profile_name(profile);return p;}
RuntimeExecutor::RuntimeExecutor(RuntimeExecutorOptions options):options_(std::move(options)){if(options_.token.empty())throw std::invalid_argument("runtime executor token required");if(!options_.command_runner)options_.command_runner=run_command;}
RuntimeResponse RuntimeExecutor::handle(std::string_view method,std::string_view path,std::string_view authorization,std::string_view body) const{
    if(method=="GET"&&path=="/health")return {200,{{"ok",true},{"service","runtime-executor"},{"mode",options_.effects_enabled?"canary-test-preview":"shadow-plan-only"},{"effects_enabled",options_.effects_enabled},{"profiles",nlohmann::json::array({"PREVIEW","TEST","HOMOLOGATION","CANARY","PRODUCTION","SEALED"})},{"live_profiles",options_.effects_enabled?nlohmann::json::array({"TEST","PREVIEW"}):nlohmann::json::array()},{"secrets_exposed",false}}};
    const std::string expected="Bearer "+options_.token;if(!constant_time_equal(authorization,expected))return {401,{{"ok",false},{"error","unauthorized"}}};if(method!="POST")return {404,{{"ok",false},{"error","not_found"}}};
    nlohmann::json request;try{request=nlohmann::json::parse(body.empty()?"{}":std::string(body));}catch(...){return {400,{{"ok",false},{"error","invalid_json"}}};}if(!request.is_object())return {422,{{"ok",false},{"error","invalid_request"}}};const auto profile=runtime_profile_from_string(request.value("profile",std::string{}));if(!profile)return {422,{{"ok",false},{"error","invalid_profile"}}};
    if(path=="/v1/execute"){if(!options_.effects_enabled)return {409,{{"ok",false},{"error","effects_not_enabled_v18"},{"effects_enabled",false},{"secrets_exposed",false}}};if(*profile!=RuntimeProfile::TEST&&*profile!=RuntimeProfile::PREVIEW)return {409,{{"ok",false},{"error","profile_effects_not_enabled_v18"},{"profile",runtime_profile_name(*profile)},{"secrets_exposed",false}}};for(auto it=request.begin();it!=request.end();++it)if(it.key()!="profile"&&it.key()!="execution_id"&&it.key()!="artifact_image_id"&&it.key()!="immutable_source_digest"&&it.key()!="ttl_seconds")return {422,{{"ok",false},{"error","unexpected_field"},{"field",it.key()}}};return execute_canary(options_,*profile,request);}
    if(path!="/v1/plan")return {404,{{"ok",false},{"error","not_found"}}};for(auto it=request.begin();it!=request.end();++it)if(it.key()!="profile"&&it.key()!="ttl_seconds")return {422,{{"ok",false},{"error","unexpected_field"},{"field",it.key()}}};auto plan=runtime_profile_policy(*profile);if(*profile==RuntimeProfile::PREVIEW){int ttl=3600;try{if(request.contains("ttl_seconds"))ttl=request.at("ttl_seconds").get<int>();}catch(...){return {422,{{"ok",false},{"error","invalid_ttl"}}};}if(ttl<300||ttl>86400)return {422,{{"ok",false},{"error","ttl_not_allowed"}}};plan["ttl_seconds"]=ttl;}else if(request.contains("ttl_seconds"))return {422,{{"ok",false},{"error","ttl_only_allowed_for_preview"}}};return {200,{{"ok",true},{"side_effect_free",true},{"effects_enabled",options_.effects_enabled},{"plan",std::move(plan)},{"secrets_exposed",false}}};
}
RuntimeExecutorOptions runtime_executor_options_from_environment(){RuntimeExecutorOptions o;o.bind_address=env_or("CLOUDIFF_RUNTIME_EXECUTOR_BIND","127.0.0.1");o.port=static_cast<unsigned short>(env_int("CLOUDIFF_RUNTIME_EXECUTOR_PORT",18232,1,65535));o.token=env_or("CLOUDIFF_RUNTIME_EXECUTOR_TOKEN");o.effects_enabled=env_bool("CLOUDIFF_RUNTIME_EXECUTOR_EFFECTS_ENABLED",false);return o;}
int run_runtime_executor_server(const RuntimeExecutorOptions& options){RuntimeExecutor executor(options);asio::io_context io;tcp::acceptor acceptor(io,{asio::ip::make_address(options.bind_address),options.port});acceptor.set_option(asio::socket_base::reuse_address(true));for(;;){tcp::socket socket(io);acceptor.accept(socket);try{beast::flat_buffer buffer;http::request_parser<http::string_body> parser;parser.body_limit(kMaxBody);http::read(socket,buffer,parser);auto req=parser.release();std::string target(req.target());if(auto q=target.find('?');q!=std::string::npos)target.resize(q);const auto av=req[http::field::authorization];const std::string auth(av.data(),av.size());auto r=executor.handle(req.method_string(),target,auth,req.body());http::response<http::string_body> res{static_cast<http::status>(r.status),req.version()};res.set(http::field::content_type,"application/json");res.set(http::field::cache_control,"no-store");res.set("X-Content-Type-Options","nosniff");res.keep_alive(false);res.body()=r.body.dump();res.prepare_payload();http::write(socket,res);beast::error_code ec;socket.shutdown(tcp::socket::shutdown_send,ec);}catch(const std::exception&){} } }
}
