#!/usr/bin/env python3
import html,json
APPROVAL_URL='/cloudiff/portal/?tab=aprovacoes'
FORGEJO_BASE='https://cloudiff.duckdns.org/git/cloudif/'
KOMODO_URL='https://komodoiff.duckdns.org/auth/oidc/login'
TOOL_DOC={
'project.list':('Listar projetos','Mostra os projetos que a identidade pode acessar.','Nenhuma','Portal CloudIFF'),
'project.get':('Consultar o projeto','Exibe metadados e estado seguro do projeto atual.','Nenhuma','Portal CloudIFF'),
'project.connectors':('Ver conectores','Mostra se Forgejo, Supabase, Workspace, Komodo e MCP estão prontos.','Nenhuma','Portal CloudIFF'),
'runtime.catalog':('Catálogo de runtimes','Lista frameworks, versões e limites homologados pela política server-side.','Nenhuma','Portal CloudIFF'),
'runtime.detect':('Detectar framework','Analisa evidências sanitizadas do repositório e sugere framework, runtime e gerenciador.','Nenhuma','Portal CloudIFF'),
'runtime.plan':('Planejar runtime e build','Gera configuração declarativa e comandos derivados somente de templates homologados.','Nenhuma','Portal CloudIFF'),
'runtime.validate':('Validar configuração','Confirma runtime, versão, gerenciador, porta e comandos contra a política vigente.','Nenhuma','Portal CloudIFF'),
'build.plan':('Planejar build','Gera plano imutável, digest e comandos derivados da política, sem executar build.','Nenhuma','Portal CloudIFF'),
'build.request':('Solicitar build','Reserva build estático idempotente na fila durável.','Conforme escopo do projeto','Portal CloudIFF'),
'build.status':('Status do build','Consulta fila, lease, tentativas e resultado sanitizado.','Nenhuma','Portal CloudIFF'),
'build.logs.read':('Logs do build','Lê logs sanitizados, sem tokens ou segredos.','Nenhuma','Portal CloudIFF'),
'build.artifact.get':('Artefato do build','Obtém digest e metadados do artefato, sem download arbitrário.','Nenhuma','Portal CloudIFF'),
'deployment.preview.plan':('Planejar preview','Valida build e expiração sem criar URL ou efeito.','Nenhuma','Portal CloudIFF'),
'deployment.preview.status':('Status do preview','Consulta ciclo de vida e expiração do preview.','Nenhuma','Portal CloudIFF'),
'approval.request-preview':('Solicitar aprovação de preview','Cria decisão humana vinculada ao digest do preview.','Portal CloudIFF','Portal CloudIFF'),
'deployment.preview':('Validar preview aprovado','Executa preview isolado e consome aprovação com reserve-effect-finalize.','Portal CloudIFF','Portal CloudIFF'),
'workspace.probe':('Verificar workspace','Confirma se o workspace pode ser usado antes de preparar arquivos.','Nenhuma','Portal CloudIFF'),
'workspace.prepare':('Preparar workspace','Cria uma cópia isolada do repositório para análise e testes.','Nenhuma','Portal CloudIFF'),
'workspace.validate':('Validar projeto','Executa validações estruturais sem publicar alterações.','Nenhuma','Portal CloudIFF'),
'workspace.test-static':('Testar conteúdo estático','Executa testes seguros para sites e arquivos estáticos.','Nenhuma','Portal CloudIFF'),
'workspace.preview-static':('Gerar prévia','Cria uma visualização temporária antes de propor mudanças.','Nenhuma','Portal CloudIFF'),
'workspace.edit-preview':('Pré-visualizar edição','Aplica a edição somente na prévia isolada.','Nenhuma','Portal CloudIFF'),
'forgejo.propose-edit.plan':('Planejar alteração','Mostra arquivos e efeitos previstos antes de criar uma proposta.','Nenhuma','Forgejo'),
'approval.request-proposal':('Solicitar aprovação da proposta','Cria uma decisão pendente para autorizar a criação do Pull Request.','Portal CloudIFF','Portal CloudIFF'),
'forgejo.propose-edit':('Criar proposta','Cria branch e Pull Request no Forgejo após aprovação.','Portal CloudIFF','Forgejo'),
'approval.get':('Consultar aprovação','Mostra o estado da aprovação solicitada pelo agente.','Nenhuma','Portal CloudIFF'),
'forgejo.proposal.list':('Listar propostas','Lista Pull Requests e propostas do projeto.','Nenhuma','Forgejo'),
'forgejo.proposal.close':('Fechar proposta','Fecha uma proposta sem mesclar o código.','Conforme política do perfil','Forgejo'),
'forgejo.proposal.delete-branch':('Apagar branch da proposta','Remove a branch temporária após encerramento.','Conforme política do perfil','Forgejo'),
'forgejo.proposal.merge.plan':('Planejar merge','Verifica se o Pull Request pode ser mesclado com segurança.','Nenhuma','Forgejo'),
'approval.request-merge':('Solicitar aprovação do merge','Cria uma decisão humana para mesclar o Pull Request.','Portal CloudIFF','Portal CloudIFF'),
'forgejo.proposal.merge':('Mesclar Pull Request','Executa o merge transacional após aprovação.','Portal CloudIFF','Forgejo'),
'supabase.migrations.inspect':('Inspecionar migrações','Lista nomes, hashes e tamanhos das migrações versionadas, sem expor SQL.','Nenhuma','Supabase Studio'),
'supabase.migrations.plan':('Planejar migrações','Gera um plano sem efeitos no ambiente isolado.','Nenhuma','Supabase Studio'),
'deployment.production.activation.plan':('Planejar ativação real','Gera digest canônico do alvo selado, snapshot, janela, canário, restauração e rollback; nunca executa efeitos.','Nenhuma','Portal CloudIFF'),
'approval.request-production-activation':('Solicitar dupla aprovação de ativação','Cria aprovação vinculada ao digest exato do plano; mudanças posteriores invalidam a autorização.','Portal CloudIFF','Portal CloudIFF'),
'deployment.production.readiness':('Verificar prontidão de produção','Mostra stack, URL, smoke, rollback, restauração do banco e demais bloqueios sem executar nada.','Nenhuma','Portal CloudIFF'),
'deployment.production.homologation.plan':('Planejar produção de homologação','Gera o digest canônico do deploy blue/green no alvo descartável, sem executar efeitos.','Nenhuma','Portal CloudIFF'),
'approval.request-production-homologation':('Solicitar aprovação de produção de homologação','Cria aprovação humana de uso único para deploy ou rollback no alvo descartável.','Portal CloudIFF','Portal CloudIFF'),
'deployment.production.homologation.deploy':('Publicar na produção de homologação','Executa troca blue/green com artefato atestado e consome a aprovação transacional.','Portal CloudIFF','Komodo'),
'deployment.production.homologation.rollback':('Reverter produção de homologação','Retorna atomicamente ao release anterior com aprovação separada de uso único.','Portal CloudIFF','Komodo'),
'deployment.production.plan':('Planejar produção','Valida commit e versão e informa se a execução pode ser liberada. Não publica enquanto houver bloqueios.','Nenhuma','Komodo'),
'deployment.plan':('Planejar deploy','Valida versão, commit e pré-condições sem executar deploy.','Nenhuma','Komodo'),
'approval.request-deploy':('Solicitar aprovação de validação','Cria uma decisão humana para a validação controlada.','Portal CloudIFF','Portal CloudIFF'),
'deployment.validate':('Validar deploy','Executa validação aprovada sem publicar em produção.','Portal CloudIFF','Komodo'),
'deployment.promote-test.plan':('Planejar promoção de teste','Prepara o deploy real somente no ambiente isolated-test.','Nenhuma','Komodo'),
'approval.request-promote-test':('Solicitar aprovação do deploy de teste','Cria a decisão humana para publicar no ambiente isolado.','Portal CloudIFF','Portal CloudIFF'),
'deployment.promote-test':('Publicar no ambiente isolado','Executa backup, deploy e smoke após aprovação.','Portal CloudIFF','Komodo'),
'deployment.promote-test.status':('Consultar status do deploy','Mostra o estado sanitizado de um job de promoção.','Nenhuma','Komodo'),
'deployment.rollback-test.plan':('Planejar rollback','Seleciona uma release histórica publicada e verifica o estado atual.','Nenhuma','Komodo'),
'approval.request-rollback-test':('Solicitar aprovação do rollback','Cria a decisão humana para restaurar uma release histórica.','Portal CloudIFF','Portal CloudIFF'),
'deployment.rollback-test':('Executar rollback isolado','Faz backup, restaura a release e executa smoke após aprovação.','Portal CloudIFF','Komodo'),
}
SCOPE_TOOLS={
'project:read':['project.list','project.get','project.connectors','runtime.catalog','runtime.detect','runtime.plan','runtime.validate','build.plan','build.status','build.logs.read','build.artifact.get','deployment.production.readiness'],'workspace:probe':['workspace.probe'],'workspace:prepare':['workspace.prepare'],'workspace:validate':['workspace.validate'],'workspace:test-static':['workspace.test-static'],'workspace:preview-static':['workspace.preview-static'],'workspace:edit-preview':['workspace.edit-preview'],'forgejo:plan-edit':['forgejo.propose-edit.plan'],'approval:request-proposal':['approval.request-proposal'],'forgejo:propose-edit':['forgejo.propose-edit'],'approval:read-own':['approval.get'],'forgejo:proposal-read':['forgejo.proposal.list'],'forgejo:proposal-close':['forgejo.proposal.close'],'forgejo:proposal-delete-branch':['forgejo.proposal.delete-branch'],'forgejo:proposal-merge-plan':['forgejo.proposal.merge.plan'],'approval:request-merge':['approval.request-merge'],'forgejo:proposal-merge':['forgejo.proposal.merge'],'supabase:migration-inspect':['supabase.migrations.inspect'],'supabase:migration-plan':['supabase.migrations.plan'],'deployment:production-plan':['deployment.production.plan','deployment.production.homologation.plan','deployment.production.homologation.deploy','deployment.production.homologation.rollback','deployment.production.activation.plan'],'deployment:plan':['deployment.plan'],'approval:request-deploy':['approval.request-deploy','approval.request-production-homologation','approval.request-production-activation'],'deployment:validate':['deployment.validate'],'approval:request-preview':['approval.request-preview'],'deployment:preview':['deployment.preview'],'deployment:promote-test-plan':['deployment.promote-test.plan'],'approval:request-promote-test':['approval.request-promote-test'],'deployment:promote-test':['deployment.promote-test'],'deployment:promote-test-status':['deployment.promote-test.status'],'deployment:rollback-test-plan':['deployment.rollback-test.plan'],'approval:request-rollback-test':['approval.request-rollback-test'],'deployment:rollback-test':['deployment.rollback-test']}
ROLE_LABELS={'viewer':'Visualizador','developer':'Desenvolvedor','maintainer':'Mantenedor','release-manager':'Gestor de releases','project-admin':'Administrador do projeto','test-operator':'Operador do ambiente isolado','custom':'Personalizado'}
def e(v):return html.escape(str(v if v is not None else ''))
def tools(scopes):
 out=[]
 for s in scopes or []:out.extend(SCOPE_TOOLS.get(s,[]))
 return sorted(set(out))
def links(row):
 slug=row.get('project_slug') or '';tenant=row.get('tenant') or '';return {'approvals':APPROVAL_URL,'forgejo':FORGEJO_BASE+'cloudif-'+slug,'supabase':f'https://{tenant}.cloudiff.duckdns.org/project/default' if tenant else '','komodo':KOMODO_URL}
def guide_data(rows):
 ps=[]
 for x in rows:
  ts=tools(x.get('scopes') or []);ps.append({'project_slug':x.get('project_slug'),'client_id':x.get('client_id'),'role_profile':x.get('role_profile'),'environment':x.get('environment'),'mcp_endpoint':(x.get('instructions') or {}).get('mcp_endpoint') or 'https://cloudiff.duckdns.org/cloudiff/mcp','tools':[dict(name=t,title=TOOL_DOC[t][0],purpose=TOOL_DOC[t][1],approval=TOOL_DOC[t][2],portal=TOOL_DOC[t][3]) for t in ts],'links':links(x),'credential_included':False,'production_enabled':False})
 return {'ok':True,'projects':ps,'secrets_exposed':False,'production_enabled':False,'documentation_version':'127A','documentation_policy':'Toda nova função MCP deve ter finalidade, uso, aprovação e portal documentados antes da homologação.','production_policy':{'homologacao':'uma aprovação por operação','ativacao_real':'dois administradores ou professores distintos','requester_cannot_approve_activation':True,'two_approvers_required_for_activation':True},'agent_discovery':{'initialize_instructions':True,'resources':['cloudiff://guide/agent','cloudiff://guide/project/{slug}'],'prompts':['cloudiff-project-workflow','cloudiff-production-policy']}}
def config_json(ep,cid):return json.dumps({'mcpServers':{'cloudiff':{'type':'http','url':ep,'headers':{'Authorization':'Bearer ${CLOUDIFF_TOKEN}','X-CloudIF-Client':cid}}}},ensure_ascii=False,indent=2)
def render(rows,csrf_token=''):
 cards=[]
 for x in rows:
  slug=x.get('project_slug') or '';cid=x.get('client_id') or '';role=x.get('role_profile') or 'custom';ep=(x.get('instructions') or {}).get('mcp_endpoint') or 'https://cloudiff.duckdns.org/cloudiff/mcp';ts=tools(x.get('scopes') or []);ln=links(x)
  toolrows=''.join(f'<tr><td><code>{e(t)}</code></td><td><b>{e(TOOL_DOC[t][0])}</b><br><span class="small">{e(TOOL_DOC[t][1])}</span></td><td>{e(TOOL_DOC[t][2])}</td><td>{e(TOOL_DOC[t][3])}</td></tr>' for t in ts)
  portal_buttons=f'<a class="btn secondary" href="{e(ln["approvals"])}">Abrir aprovações no Portal CloudIFF</a> <a class="btn light" target="_blank" href="{e(ln["forgejo"])}">Abrir Forgejo</a> '+(f'<a class="btn light" target="_blank" href="{e(ln["supabase"])}">Abrir Supabase Studio</a> ' if ln['supabase'] else '')+f'<a class="btn light" target="_blank" href="{e(ln["komodo"])}">Abrir Komodo</a>'
  cards.append(f'''<article class="card"><h2>{e(slug)}</h2><p>{e(ROLE_LABELS.get(role,role))} · <code>{e(x.get('environment') or 'project')}</code></p><div class="box"><b>Onde cada ação acontece</b><p><b>Aprovar ou rejeitar:</b> Portal CloudIFF. <b>Revisar código:</b> Forgejo. <b>Consultar banco:</b> Supabase Studio. <b>Acompanhar execução:</b> Komodo.</p>{portal_buttons}</div><div class="grid"><div class="box"><b>Endpoint MCP</b><code>{e(ep)}</code></div><div class="box"><b>Client ID</b><code>{e(cid)}</code></div><div class="box"><b>Token</b><p>Use “Rotacionar e exibir uma vez”.</p><a class="btn secondary" href="/cloudiff/portal/?tab=projetos#project-identities">Obter token</a></div></div><details open><summary><b>Configuração MCP genérica</b></summary><pre>{e(config_json(ep,cid))}</pre></details><details open><summary><b>Ferramentas autorizadas — o que cada permissão permite</b></summary><table><tr><th>Ferramenta</th><th>Para que serve</th><th>Aprovação</th><th>Portal relacionado</th></tr>{toolrows}</table></details></article>''')
 intro='''<section class="card"><h1>Agentes de IA</h1><span class="pill ok">Produção desabilitada</span><p>Use MCP com isolamento por projeto, aprovações humanas e auditoria.</p><h2>Como funcionam as aprovações</h2><div class="infra-note"><b>Aprovação humana:</b> acontece exclusivamente no <b>Portal CloudIFF</b>. Forgejo, Supabase e Komodo não substituem a decisão de aprovação.</div><p><a class="btn secondary" href="/cloudiff/portal/?tab=aprovacoes">Abrir aprovações humanas</a> <a class="btn light" href="/cloudiff/portal/?tab=capacidades">Ver capacidades dos projetos</a> <a class="btn light" href="/cloudiff/portal/?tab=reconciliacao">Acompanhar reconciliação</a></p></section>'''
 token='''<section class="card" id="como-obter-token"><h2>Como obter seu token</h2><div class="grid"><div class="box"><h3>Linux ou macOS</h3><code>export CLOUDIFF_TOKEN='cole_o_token_aqui'</code></div><div class="box"><h3>PowerShell</h3><code>$env:CLOUDIFF_TOKEN = 'cole_o_token_aqui'</code></div><div class="box"><h3>Arquivo .env local</h3><code>CLOUDIFF_TOKEN=cole_o_token_aqui</code><p>Inclua <code>.env</code> no <code>.gitignore</code>.</p></div></div><p><b>Nunca:</b> exponha a credencial.</p><ol><li>Abra o projeto.</li><li>Clique em <b>Rotacionar e exibir uma vez</b>.</li><li>Copie o token imediatamente.</li><li>Salve como <code>CLOUDIFF_TOKEN</code> no seu computador.</li><li>Nunca coloque o token em prompts, Git, issues ou documentação.</li></ol><pre>export CLOUDIFF_TOKEN='cole_o_token_aqui'\n$env:CLOUDIFF_TOKEN = 'cole_o_token_aqui'\nCLOUDIFF_TOKEN=cole_o_token_aqui</pre></section>'''
 reconciliation='''<section class="card"><h2>Reconciliação assíncrona</h2><p>Novos projetos e atualizações entram em uma fila durável particionada por projeto. Até quatro projetos podem avançar em paralelo, sem que um projeto lento bloqueie os outros.</p><ul><li>Uma tarefa ativa por projeto.</li><li>Lease de 45 segundos com recuperação automática.</li><li>Retry exponencial com jitter e até cinco tentativas.</li><li>Dead-letter para falhas permanentes.</li><li>Coalescência de eventos repetidos.</li><li>Tokens e segredos são proibidos no payload da fila.</li><li>Rotação de credencial não invalida tarefas pendentes.</li></ul><p><a class="btn light" href="/cloudiff/portal/?tab=reconciliacao">Abrir fila de reconciliação</a></p></section>'''
 production='''<section class="card" id="production-policy"><h2>Política de produção</h2><div class="grid"><div class="box"><h3>Homologação</h3><p>Cada deploy ou rollback exige uma aprovação humana própria e de uso único.</p></div><div class="box"><h3>Ativação real</h3><p>Exige dois administradores ou professores distintos. O solicitante não pode aprovar.</p></div><div class="box"><h3>Bloqueios técnicos</h3><p>Janela de mudança aberta, snapshot obrigatório, rollback verificado e efeitos explicitamente habilitados.</p></div></div><div class="infra-note"><b>A produção real continua desabilitada.</b> A pré-ativação exige dupla aprovação, mas não existe ferramenta de execução real liberada.</div></section>'''
 discovery='''<section class="card" id="agent-discovery"><h2>Como o agente aprende a usar a CloudIFF</h2><p>Clientes MCP como ChatGPT, Claude e agentes Llama compatíveis recebem orientação automaticamente ao conectar.</p><table><tr><th>Recurso MCP</th><th>Finalidade</th></tr><tr><td><code>initialize.instructions</code></td><td>Regras gerais, portais, aprovações e limites.</td></tr><tr><td><code>cloudiff://guide/agent</code></td><td>Guia geral legível pelo agente.</td></tr><tr><td><code>cloudiff://guide/project/{slug}</code></td><td>Fluxo seguro do projeto autorizado.</td></tr><tr><td><code>cloudiff-project-workflow</code></td><td>Prompt inicial para trabalhar no projeto.</td></tr><tr><td><code>cloudiff-production-policy</code></td><td>Explica quem pode autorizar produção.</td></tr></table><p>O agente deve começar por <code>resources/list</code>, ler o guia do projeto e depois consultar <code>tools/list</code>.</p></section>'''
 policy='''<section class="card"><h2>Diretiva permanente de documentação</h2><p>Toda nova função ativada no MCP autenticado e distribuído deve, antes da homologação:</p><ol><li>aparecer nesta página;</li><li>explicar para que serve e quando usar;</li><li>informar se exige aprovação e onde aprovar;</li><li>indicar o portal relacionado;</li><li>ser coberta por smoke que compara o catálogo MCP com a documentação.</li></ol></section>'''
 return intro+token+reconciliation+production+discovery+policy+''.join(cards)
