import cloudif_portal_publications as _prodpub
import cloudif_ui_publications as _legacy_pub
import html,json,os,sqlite3,time,urllib.request
DB='/var/lib/cloudif/build-broker/builds.sqlite3'
POLICY='/etc/cloudif/runtime-policy.json'
PREVIEW_DB='/var/lib/cloudif/preview-broker/previews.sqlite3'
NODE24='/etc/cloudif/node24-homologation.json'
def node24_status():
 try:
  x=json.load(open(NODE24));return {'ready':bool(x.get('ok') and x.get('status')=='ready' and not x.get('scanner_blocked')),'sbom_components':x.get('sbom_components'),'scanner_counts':x.get('scanner_counts') or {},'node_version':x.get('node_version')}
 except Exception:return {'ready':False,'node_version':'24','sbom_components':0,'scanner_counts':{}}

def data(visible):
 visible=[dict(p) if not isinstance(p,dict) else p for p in visible]
 allowed={str(p.get('slug')) for p in visible if p.get('slug')}
 policy=json.load(open(POLICY))
 rows=[]
 if os.path.exists(DB):
  c=sqlite3.connect('file:'+DB+'?mode=ro',uri=True);c.row_factory=sqlite3.Row
  for r in c.execute('SELECT id,project_slug,ref,framework,plan_digest,status,created_at,updated_at,attempts,result_json,next_attempt_at,dead_reason FROM builds ORDER BY created_at DESC LIMIT 100'):
   if r['project_slug'] not in allowed:continue
   x=dict(r);x['result']=json.loads(x.pop('result_json') or 'null');x['secrets_exposed']=False;rows.append(x)
 preview_by={}
 if os.path.exists(PREVIEW_DB):
  pc=sqlite3.connect('file:'+PREVIEW_DB+'?mode=ro',uri=True);pc.row_factory=sqlite3.Row
  for r in pc.execute("SELECT id,project_slug,status,expires_at,url,result_json FROM previews WHERE status IN ('active','validated') ORDER BY created_at DESC"):
   if r['project_slug'] in allowed and r['project_slug'] not in preview_by:
    x=dict(r);x['result']=json.loads(x.pop('result_json') or 'null');preview_by[r['project_slug']]=x
 by={s:[] for s in allowed}
 for x in rows:by.setdefault(x['project_slug'],[]).append(x)
 projects=[]
 for p in visible:
  slug=p.get('slug'); hist=by.get(slug,[]); current=hist[0] if hist else None
  projects.append({'slug':slug,'name':p.get('name') or slug,'framework_detected':(current or {}).get('framework'),'framework_selected':(current or {}).get('framework'),'runtime_policy_version':policy.get('policy_version'),'runtime_versions':policy.get('runtimes',{}).get('node',{}).get('versions',[]),'build_current':current,'build_history':hist[:10],'preview':({'ready':True,'status':preview_by[slug]['status'],'url':preview_by[slug]['url'],'expires_at':preview_by[slug]['expires_at']} if slug in preview_by else {'ready':False,'status':'not_configured'}),'production':(_prodpub.production_status(slug) if slug==_prodpub.TARGET_SLUG else {'ready':False,'status':'versioned'}),'rollback':{'ready':False,'status':'not_configured'}})
 return {'ok':True,'policy_version':policy.get('policy_version'),'frameworks':sorted(policy.get('frameworks',{})),'projects':projects,'builds':rows,'queue':{'queued':sum(x['status']=='queued' for x in rows),'running':sum(x['status']=='running' for x in rows),'failed':sum(x['status']=='failed' for x in rows),'dead_letter':sum(x['status']=='dead_letter' for x in rows)},'production_effects_enabled':True,'secrets_exposed':False}
def render(visible):
 d=data(visible); cards=[]
 for p in d['projects']:
  b=p['build_current']; status=(b or {}).get('status','sem build'); color='healthy' if status=='succeeded' else ('attention' if status in ('queued','running') else ('error' if status in ('failed','dead_letter') else 'inactive'))
  pub=p.get('production') or {};is_real=p['slug']==_prodpub.TARGET_SLUG;active=bool(pub.get('public_traffic'));real_controls=(('<div class="cm-resource production-live"><div class="cm-resource-title"><strong>Produção real</strong><span class="pill '+('ok' if active else 'bad')+'">'+('Ativa' if active else 'Inativa')+'</span></div><div class="cm-actions"><a class="btn light" href="'+_prodpub.PRODUCTION_URL+'" target="_blank" rel="noopener">Abrir site publicado</a><form method="post" action="/cloudiff/portal/action/publication"><input type="hidden" name="slug" value="'+html.escape(p['slug'])+'"><button class="btn" name="op" value="publish_version">Publicar site</button></form>'+('<form method="post" action="/cloudiff/portal/action/publication"><input type="hidden" name="slug" value="'+html.escape(p['slug'])+'"><button class="btn red" name="op" value="rollback_production">Rollback</button></form>' if pub.get('current',{}).get('previous_release_id') else '')+'</div><p class="small">Blue/green, health externo e rollback automático.</p></div>') if is_real else _legacy_pub.publication_panel(p['slug']));cards.append(f'''<article class="publication-project card"><div class="publication-head"><div><h2>{html.escape(p['name'])}</h2><code>{html.escape(p['slug'])}</code></div><span class="state {color}">{html.escape(status)}</span></div><div class="publication-grid"><div><span>Framework</span><strong>{html.escape(p['framework_detected'] or 'A detectar')}</strong></div><div><span>Política</span><strong>{html.escape(str(p['runtime_policy_version']))}</strong></div><div><span>Preview</span><strong>{('Ativo' if p['preview']['ready'] else 'Não configurado')}</strong></div><div><span>Segurança</span><strong>{('SBOM + scan OK' if b and (b.get('result') or {}).get('sbom_ready') and (b.get('result') or {}).get('scanner_ready') and not (b.get('result') or {}).get('scanner_blocked') else 'Pendente')}</strong></div><div><span>Produção</span><strong class="{'text-ok' if active else 'text-error'}">{'Ativa' if active else ('Disponível' if not is_real else 'Inativa')}</strong></div></div><div class="publication-flow"><span class="done">1 Detecção</span><span class="{'done' if b else ''}">2 Plano</span><span class="{'done' if status=='succeeded' else ''}">3 Build</span><span>4 Preview</span><span>5 Aprovação</span><span>6 Produção</span><span>7 Rollback</span></div><p class="small">Comandos são derivados da política. Produção permanece fail-closed até imagem, SBOM, scanner, health check e rollback.</p>{real_controls}</article>''')
 return '''<section class="publication-shell"><div class="page-hero"><div><span class="eyebrow">Meus Projetos</span><h1>Publicação</h1><p>Configuração, build, preview, produção e rollback em um único fluxo.</p></div><div class="hero-stats"><strong>'''+str(len(d['projects']))+''' projetos</strong><span>Política '''+html.escape(str(d['policy_version']))+'''</span></div></div><div class="publication-summary card"><div><strong>Fila</strong><span>'''+str(d['queue']['queued'])+''' aguardando</span><span>'''+str(d['queue']['running'])+''' em execução</span><span>'''+str(d['queue']['dead_letter'])+''' dead-letter</span></div><div class="security-note">Produção real habilitada para administradores autorizados; publicações usam health e rollback.</div></div>'''+''.join(cards)+'''</section><style>.publication-shell{display:grid;gap:18px}.page-hero,.publication-head,.publication-summary>div{display:flex;align-items:center;justify-content:space-between;gap:16px}.page-hero{padding:24px;border-radius:18px;background:linear-gradient(135deg,#edf7f0,#f8fbff);border:1px solid #d7e4da}.eyebrow{color:#176b35;font-weight:900;text-transform:uppercase;font-size:.75rem}.hero-stats{display:grid;text-align:right}.publication-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.publication-grid>div{padding:12px;border:1px solid #e0e8e2;border-radius:12px;background:#fafcfb}.publication-grid span{display:block;color:#6d7b72;font-size:.8rem}.publication-flow{display:flex;gap:8px;flex-wrap:wrap}.publication-flow span{padding:7px 10px;border-radius:999px;background:#edf0ee;color:#66726a;font-weight:800;font-size:.78rem}.publication-flow .done{background:#dff3e5;color:#176b35}.state{padding:6px 10px;border-radius:999px;font-weight:900}.state.healthy{background:#dff3e5;color:#176b35}.state.attention{background:#fff3cd;color:#8a6200}.state.error{background:#fde2e2;color:#a22121}.state.inactive{background:#ecefed;color:#69736d}.text-error{color:#a22121}.text-ok{color:#176b35}.cm-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.cm-resource{margin-top:16px;padding:14px;border:1px solid #d7e4da;border-radius:12px}.cm-resource-title{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:10px}@media(max-width:800px){.publication-grid{grid-template-columns:1fr 1fr}.page-hero{align-items:flex-start;flex-direction:column}.hero-stats{text-align:left}}</style>'''
