#!/usr/bin/env python3
"""Offline integrity and secret validation for the CloudIFF source repository."""
from __future__ import annotations

import ast
import collections
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ERRORS: list[str] = []
STATS: dict[str, int] = {}


def fail(message: str) -> None:
    ERRORS.append(message)


def files(pattern: str) -> list[Path]:
    return [p for p in ROOT.rglob(pattern) if ".git" not in p.parts and p.is_file()]


def validate_forbidden_files() -> None:
    forbidden_names = {".env", "id_rsa", "id_ed25519"}
    forbidden_suffixes = {".pem", ".key", ".p12", ".pfx", ".db", ".sqlite", ".sqlite3", ".log", ".pyc"}
    for p in ROOT.rglob("*"):
        if ".git" in p.parts or not p.is_file():
            continue
        if p.name in forbidden_names or p.suffix.lower() in forbidden_suffixes:
            # Public verification keys deliberately use .pub and are allowed.
            fail(f"forbidden runtime/secret file: {p.relative_to(ROOT)}")
        if "__pycache__" in p.parts:
            fail(f"generated bytecode directory: {p.relative_to(ROOT)}")


def validate_secrets() -> None:
    patterns = {
        "private key": re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
        "GitHub token": re.compile(r"gh[pousr]_[A-Za-z0-9_]{30,}"),
        "JWT": re.compile(r"eyJ[A-Za-z0-9_-]{15,}\.[A-Za-z0-9_-]{15,}\.[A-Za-z0-9_-]{15,}"),
        "authenticated URL": re.compile(r"https?://[^\s/:@]+:[^\s/@]+@"),
        "literal bearer": re.compile(r"(?i)Authorization[\"']?\s*[:=]\s*[\"']Bearer\s+[A-Za-z0-9._-]{20,}"),
        "systemd literal secret": re.compile(
            r"(?im)^Environment\s*=.*(?:TOKEN|PASSWORD|PASSWD|SECRET|API_KEY|CLIENT_SECRET)=[^$%{<\s][^\s]*"
        ),
    }
    for p in ROOT.rglob("*"):
        if ".git" in p.parts or not p.is_file() or p.stat().st_size > 2_000_000:
            continue
        try:
            text = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for label, regex in patterns.items():
            for match in regex.finditer(text):
                line = text.count("\n", 0, match.start()) + 1
                fail(f"{label} in {p.relative_to(ROOT)}:{line}")


def validate_python() -> None:
    py_files = files("*.py")
    STATS["python"] = len(py_files)
    local_modules = {p.stem for p in py_files}
    referenced: set[str] = set()
    for p in py_files:
        try:
            source = p.read_text(encoding="utf-8")
            compile(source, str(p), "exec")
            tree = ast.parse(source, filename=str(p))
        except Exception as exc:  # noqa: BLE001
            fail(f"python syntax: {p.relative_to(ROOT)}: {exc}")
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                referenced.update(a.name.split(".")[0] for a in node.names if a.name.startswith("cloudif_"))
            elif isinstance(node, ast.ImportFrom) and node.module and node.module.startswith("cloudif_"):
                referenced.add(node.module.split(".")[0])
    for module in sorted(referenced - local_modules):
        fail(f"missing local Python module: {module}")


def validate_shell() -> None:
    sh_files = files("*.sh")
    STATS["shell"] = len(sh_files)
    for p in sh_files:
        result = subprocess.run(["bash", "-n", str(p)], capture_output=True, text=True)
        if result.returncode:
            fail(f"shell syntax: {p.relative_to(ROOT)}: {result.stderr.strip()}")


def validate_json() -> None:
    json_files = files("*.json")
    STATS["json"] = len(json_files)
    for p in json_files:
        try:
            json.loads(p.read_text(encoding="utf-8"))
        except Exception as exc:  # noqa: BLE001
            fail(f"JSON syntax: {p.relative_to(ROOT)}: {exc}")


def validate_yaml() -> None:
    yaml_files = files("*.yml") + files("*.yaml")
    STATS["yaml"] = len(yaml_files)
    try:
        import yaml  # type: ignore
    except ImportError:
        print("WARN PyYAML unavailable; YAML syntax validation skipped", file=sys.stderr)
        return
    class ComposeLoader(yaml.SafeLoader):
        pass

    def compose_tag(loader, tag_suffix, node):
        if isinstance(node, yaml.ScalarNode):
            return loader.construct_scalar(node)
        if isinstance(node, yaml.SequenceNode):
            return loader.construct_sequence(node)
        return loader.construct_mapping(node)

    ComposeLoader.add_multi_constructor("!", compose_tag)
    for p in yaml_files:
        try:
            yaml.load(p.read_text(encoding="utf-8"), Loader=ComposeLoader)
        except Exception as exc:  # noqa: BLE001
            fail(f"YAML syntax: {p.relative_to(ROOT)}: {exc}")


def validate_unit_references() -> None:
    components = {
        "control-plane": ROOT / "components/control-plane",
        "runtime": ROOT / "components/runtime",
        "proxy": ROOT / "components/proxy",
    }
    absolute = re.compile(r"(/(?:usr/local/sbin|srv/cloudif/app-pointers|srv/cloudif/bin)/[^\s;\"']+)")
    checked = 0
    for name, base in components.items():
        unit_dir = base / "etc/systemd/system"
        for unit in unit_dir.glob("cloudif-*"):
            if not unit.is_file():
                continue
            text = unit.read_text(encoding="utf-8", errors="replace")
            for ref in absolute.findall(text):
                ref = ref.rstrip(")")
                target: Path | None = None
                if ref.startswith("/usr/local/sbin/"):
                    target = base / ref.lstrip("/")
                elif ref.startswith("/srv/cloudif/app-pointers/"):
                    rest = ref.removeprefix("/srv/cloudif/app-pointers/")
                    target = base / "current-apps" / rest
                elif ref.startswith("/srv/cloudif/bin/") and name == "control-plane":
                    target = base / ref.lstrip("/")
                if target is not None and target.suffix and not target.exists():
                    fail(f"unit reference missing: {unit.relative_to(ROOT)} -> {ref}")
                checked += 1
    STATS["unit_references"] = checked



def validate_portal_quality() -> None:
    """Prevent the v2 from inheriting the append-only legacy pattern."""
    baseline_path = ROOT / "config/portal-quality-baseline.json"
    baseline = json.loads(baseline_path.read_text(encoding="utf-8"))
    legacy = ROOT / baseline["legacy_file"]
    legacy_text = legacy.read_text(encoding="utf-8")
    legacy_important = legacy_text.count("!important")
    if legacy_important > baseline["legacy_important_max"]:
        fail(
            f"legacy !important count increased: {legacy_important} > "
            f"{baseline['legacy_important_max']}"
        )

    def duplicate_symbols(path: Path) -> dict[str, int]:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        names = collections.Counter(
            node.name
            for node in tree.body
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
        )
        return {name: count for name, count in names.items() if count > 1}

    allowed_legacy = baseline["legacy_duplicate_symbols"]
    actual_legacy = duplicate_symbols(legacy)
    if actual_legacy != allowed_legacy:
        fail(f"legacy duplicate-symbol baseline changed: {actual_legacy}")

    portal_duplicates: dict[str, dict[str, int]] = {}
    for path in (ROOT / "portal").rglob("*.py"):
        if "legacy" in path.parts:
            continue
        duplicates = duplicate_symbols(path)
        if duplicates:
            portal_duplicates[str(path.relative_to(ROOT))] = duplicates
    if portal_duplicates:
        fail(f"Portal v2 redefined symbols: {portal_duplicates}")

    tokens = ROOT / "portal/design/tokens.css"
    components = ROOT / "portal/design/components.css"
    base = ROOT / "portal/design/base.css"
    component_text = components.read_text(encoding="utf-8")
    important_count = component_text.count("!important")
    if important_count > baseline["portal_v2_components_important_max"]:
        fail(f"Portal v2 components.css contains {important_count} !important rules")

    color_literal = re.compile(r"#[0-9a-fA-F]{3,8}\b|rgba?\(")
    for path in (base, components):
        if color_literal.search(path.read_text(encoding="utf-8")):
            fail(f"color literal outside tokens.css: {path.relative_to(ROOT)}")

    # Detect byte-equivalent CSS rule bodies repeated in the v2 component sheet.
    blocks = collections.Counter()
    for selector, body in re.findall(r"([^{}]+)\{([^{}]+)\}", component_text):
        normalized_selector = re.sub(r"\s+", " ", selector).strip()
        normalized_body = re.sub(r"\s+", "", body)
        if normalized_selector and normalized_body:
            blocks[(normalized_selector, normalized_body)] += 1
    repeated = {selector: count for (selector, _body), count in blocks.items() if count > 1}
    if repeated:
        fail(f"Portal v2 duplicate CSS blocks: {repeated}")

    # No module may depend on a sibling module.
    module_names = {p.name for p in (ROOT / "portal/modules").iterdir() if p.is_dir()}
    for path in (ROOT / "portal/modules").rglob("*.py"):
        own = path.relative_to(ROOT / "portal/modules").parts[0]
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            target = None
            if isinstance(node, ast.ImportFrom) and node.module:
                target = node.module
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name.startswith("portal.modules."):
                        target = alias.name
            if target and target.startswith("portal.modules."):
                sibling = target.split(".")[2]
                if sibling in module_names and sibling != own:
                    fail(f"sibling module import: {path.relative_to(ROOT)} -> {target}")

    STATS["legacy_important"] = legacy_important
    STATS["portal_v2_important"] = important_count
    STATS["portal_v2_duplicate_symbols"] = len(portal_duplicates)
    STATS["portal_v2_duplicate_css_blocks"] = len(repeated)

def validate_structure() -> None:
    required = [
        "components/control-plane/current-apps/portal-current/cloudif-admin-portal.py",
        "components/control-plane/current-apps/monitor-current/cloudif-monitor-api.py",
        "components/control-plane/current-apps/monitor-current/cloudif-monitor-collector.py",
        "components/control-plane/current-apps/agent-registry-current/cloudif-agent-registry.py",
        "components/control-plane/current-apps/mcp-gateway-current/cloudif-mcp-gateway.py",
        "components/control-plane/srv/cloudif/lib/cloudif_project_action_safe.py",
        "components/control-plane/srv/cloudif/bin/cloudif-project-orchestrator-v4.py",
        "components/control-plane/srv/cloudif/staging/cloudif-admin-portal-staging.py",
        "components/control-plane/srv/cloudif/staging/lib/cloudif_project_action_safe.py",
        "components/control-plane/srv/cloudif/staging/lib/cloudif_project_provision_worker.py",
        "components/control-plane/srv/cloudif/staging/lib/cloudif_reconcile_client.py",
        "components/runtime/current-apps/komodo-agent-current/cloudif-komodo-agent.py",
        "components/runtime/current-apps/forja-agent-current/cloudif-forja-agent.py",
        "components/runtime/current-apps/node24-pipeline-current/cloudif-node24-pipeline.py",
        "components/runtime/srv/cloudif/test-fixtures/node24-http/package.json",
        "components/proxy/current-apps/access-telemetry-current/cloudif-access-api.py",
        "components/proxy/current-apps/publisher-agent-current/cloudif-npm-publisher-agent.py",
        "components/proxy/srv/cloudif/proxy/npm/data/nginx/custom/http.conf",
        "tenant-templates/srv/cloudif/tenants",
        "config/control-plane/portal.env.example",
        "config/runtime/forja-agent.env.example",
        "config/proxy/access-telemetry.env.example",
        "portal/app.py",
        "portal/registry.py",
        "portal/design/tokens.css",
        "portal/design/base.css",
        "portal/design/components.css",
        "portal/design/app.js",
        "portal/legacy/README.md",
        "docs/portal-v2/prototipo.html",
    ]
    for item in required:
        if not (ROOT / item).exists():
            fail(f"required path missing: {item}")


def main() -> int:
    validate_structure()
    validate_forbidden_files()
    validate_secrets()
    validate_python()
    validate_shell()
    validate_json()
    validate_yaml()
    validate_unit_references()
    validate_portal_quality()
    result = {"ok": not ERRORS, "stats": STATS, "errors": ERRORS}
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if not ERRORS else 1


if __name__ == "__main__":
    raise SystemExit(main())
